title: Documentation
doc_version: 1.1.0
url: https://icp.nlamprian.me

permalink: /:categories/:title
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
  - jemoji
  - rouge
